spring:
  main:
    allow-bean-definition-overriding: true
  batch:
    job:
      enabled: true
#    jdbc:
#      initialize-schema: embedded
  datasource:
    url: jdbc:mariadb://211.43.13.165:31838/my_database
    driver-class-name: org.mariadb.jdbc.Driver
    username: "root"
    password: "sRMNpgwRs1"
    hikari:
      jdbcUrl: jdbc:mariadb://211.43.13.165:31838/my_database
      username: "root"
      password: "sRMNpgwRs1"
      pool-name: hikari-cp
      maximum-pool-size: "30"
      minimum-idle: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true